import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/dashboard/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " relative flex flex-col justify-center h-screen w-screen items-center bg-mirage"}>
          <NavBar />
        <div className=" relative w-full h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
